#!/bin/bash
#set -eou pipefail

header () {
  printf "\n\r \033[1;37m$1\n"
}

info () {
  printf "\r  [ \033[0;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r  [ \033[0;32mOK\033[0m ] $1\n"
}

warn () {
  printf "\r  [ \033[0;33m!!\033[0m ] $1\n"
}

fail () {
  red = 
  printf "\r  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}